server:
  port: 8488
  servlet:
    context-path: /manage_system


spring:
  datasource:
    username: root
    password: 13579
    url: jdbc:mysql://localhost:3306/manage_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 3000
      connection-test-query: SELECT 1
servlet:
  multipart:
   max-file-size: 20MB
   max-request-size: 20MB    
      
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.example.study_system.model

#show sql
logging:
  level:
    com.example.study_system.dao: debug

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  
  
